# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b20430a1ab1a8f1ec593b6d4ef7db26703541bc91217b8c7b67c44732487d28f9f8c98066e0978aa741a3a82dbf6e9e7abf615a2174def94bdc57d1efd752e9

test:
  secret_key_base: 1fdec8dd358982b098f96d334c32e84ad375a2c9cbacb7f31065d6c730ffd734845f724a837caab10a7aafe5f2a87061fea055bce33a9950a867083a2098a82e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 1fdec8dd358982b098f96d334c32e84ad375a2c9cbacb7f31065d6c730ffd734845f724a837caab10a7aafe5f2a87061fea055bce33a9950a867083a2098a82e
